name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v6.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.0.0
        with:
          driver: docker-container

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v4.1.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v7.1.0
        with:
          # Build's context is the set of files located in the specified PATH or URL
          context: .
          # List of target platforms for build
          push: true
          # List of tags
          tags: ghcr.io/teammasse/battlesnake:latest
          # List of external cache sources for buildx (e.g., user/app:cache, type=local,src=path/to/dir)
          cache-from: type=gha
          # List of cache export destinations for buildx (e.g., user/app:cache, type=local,dest=path/to/dir)
          cache-to: type=gha,mode=max
                
